"""add razorpay columns

Revision ID: ca201e6ede4e
Revises: 0002
Create Date: 2026-05-27 18:03:41.123297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca201e6ede4e'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_razorpay_order_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('razorpay_customer_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_users_razorpay_order_id', ['razorpay_order_id'], unique=1)

    # ### end Alembic commands ###
